apiVersion: v1
description: A fast and secure standalone server for resizing and converting remote images. The main principles of imgproxy are simplicity, speed, and security.
name: imgproxy
icon: https://cdn.rawgit.com/imgproxy/imgproxy/master/logo.svg
version: 1.0.0
appVersion: 3.24.1
keywords:
  - imgproxy
  - image
  - processing
home: https://github.com/imgproxy/imgproxy
sources:
  - https://github.com/imgproxy/imgproxy
maintainers:
  - name: darthsim
    email: darthsim@gmail.com
  - name: dragonsmith
    email: agon.smith@gmail.com
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Support for the ArtifactHub
  artifacthub.io/containsSecurityUpdates: "false"
  artifacthub.io/images: |
    - name: impgroxy
      image: ghcr.io/imgproxy/imgproxy:v3.28.0
  artifacthub.io/license: MIT-open-group
  artifacthub.io/links: |
    - name: imgproxy-helm chart on Github
      url: https://github.com/imgproxy/imgproxy-helm
    - name: the source code of imgproxy on Github
      url: https://github.com/imgproxy/imgproxy
    - name: the project documentation
      url: https://imgproxy.net/
  artifacthub.io/prerelease: "false"
  artifacthub.io/maintainers: |
    - name: darthsim
      email: darthsim@gmail.com
    - name: dragonsmith
      email: agon.smith@gmail.com
