{{- $apiVersion := include "imgproxy.versions.horizontalPodAutoscaler" $ }}
{{- with .Values.resources.deployment.replicas | default dict -}}
{{- $minCount := .minCount | default 1 | int }}
{{- $maxCount := .maxCount | default $minCount | int }}
{{- if gt $maxCount $minCount -}}
---
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "imgproxy.fullname" $ }}-autoscaling
  labels:
    heritage: {{ $.Release.Service | quote }}
    release: {{ $.Release.Name | quote }}
    chart: {{ template "imgproxy.chart" $ }}
    app: {{ template "imgproxy.fullname" $ }}
spec:
  minReplicas: {{ $minCount }}
  maxReplicas: {{ $maxCount }}
  scaleTargetRef:
    kind: Deployment
    name: {{ template "imgproxy.fullname" $ }}
    apiVersion: apps/v1
  behavior:
    scaleDown:
      policies:
        - type: Pods
          value: {{ .stepCount | default 1 | max 1 }}
          periodSeconds: {{ .stepSeconds | default 60 | max 1 | min 1800 }}
      stabilizationWindowSeconds: {{ .stabilizationInterval | default 300 | max 0 | min 3600 }}
    scaleUp:
      policies:
        - type: Pods
          value: {{ .stepCount | default 1 | max 1 }}
          periodSeconds: {{ .stepSeconds | default 60 | max 1 | min 1800 }}
      stabilizationWindowSeconds: {{ .stabilizationInterval | default 300 | max 0 | min 3600 }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .cpuUtilization | default 80 }}
{{- end }}
{{- end }}
