{{- $apiVersion := include "imgproxy.versions.horizontalPodAutoscaler" $ }}
{{- with .Values.resources.deployment.replicas | default dict -}}
{{- $minCount := .minCount | default 1 | int }}
{{- $maxCount := .maxCount | default $minCount | int }}
{{- if gt $maxCount $minCount -}}
---
apiVersion: {{ $apiVersion }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "imgproxy.fullname" $ }}-autoscaling
  labels:
    heritage: {{ $.Release.Service | quote }}
    release: {{ $.Release.Name | quote }}
    chart: {{ template "imgproxy.chart" $ }}
    app: {{ template "imgproxy.fullname" $ }}
    {{- range $key, $val := ($.Values.resources.common.labels | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  minReplicas: {{ $minCount }}
  maxReplicas: {{ $maxCount }}
  scaleTargetRef:
    kind: Deployment
    name: {{ template "imgproxy.fullname" $ }}
    apiVersion: apps/v1
  behavior:
    scaleDown:
      {{- $scaleDown := .scaleDownBehavior | default dict }}
      policies:
        - type: Pods
          value: {{ $scaleDown.stepCount | default .stepCount | default 1 | max 1 }}
          periodSeconds: {{ $scaleDown.stepSeconds | default .stepSeconds | default 60 | max 1 | min 1800 }}
      stabilizationWindowSeconds: {{ $scaleDown.stabilizationInterval | default .stabilizationInterval | default 300 | max 0 | min 3600 }}
      {{- if $scaleDown.selectPolicy }}
      selectPolicy: {{ $scaleDown.selectPolicy }}
      {{- end }}
    scaleUp:
      {{- $scaleUp := .scaleUpBehavior | default dict }}
      policies:
        - type: Pods
          value: {{ $scaleUp.stepCount | default .stepCount | default 1 | max 1 }}
          periodSeconds: {{ $scaleUp.stepSeconds | default .stepSeconds | default 60 | max 1 | min 1800 }}
      stabilizationWindowSeconds: {{ $scaleUp.stabilizationInterval | default .stabilizationInterval | default 300 | max 0 | min 3600 }}
      {{- if $scaleUp.selectPolicy }}
      selectPolicy: {{ $scaleUp.selectPolicy }}
      {{- end }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .cpuUtilization | default 80 }}
{{- end }}
{{- end }}
