{{- $apiVersion := include "imgproxy.versions.ingress" . }}
{{- with .Values.resources.ingress }}
{{- if (.enabled | and $apiVersion | and .health.whitelist) }}
---
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ template "imgproxy.fullname" $ }}-health
  labels:
    app: {{ template "imgproxy.fullname" $ }}
    chart: {{ template "imgproxy.chart" $ }}
    release: "{{ $.Release.Name }}"
    heritage: "{{ $.Release.Service }}"
    imgproxy: "true"
  annotations:
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ .health.whitelist | quote }}
    {{- if .annotations }}
    {{- toYaml .annotations | nindent 4 }}
    {{- end }}
spec:
  {{- if .tls }}
  tls:
    {{- range .tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          {{- $name := include "imgproxy.fullname" $ }}
          {{- $path := ($.Values.features.server.pathPrefix | default "" | printf "%s/health") }}
          {{- if eq $apiVersion "networking.k8s.io/v1" }}
          - path: {{ $path | quote }}
            pathType: Exact
            backend:
              service:
                name: {{ $name | quote }}
                port:
                  number: 80
          {{- else }}
          - path: {{ $path | quote }}
            backend:
              serviceName: {{ $name | quote }}
              servicePort: 80
          {{- end }}
{{- end }}
{{- end }}
{{- end }}
