{{- with .Values.resources.serviceAccount -}}
{{- if .enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .name | quote }}
  annotations: {{ toYaml .annotations | nindent 4 }}
{{- end }}
{{- end -}}
