{{- if and (.Values.env.IMGPROXY_PROMETHEUS_BIND) (.Values.resources.serviceMonitor.enabled) }}
{{- with .Values.resources.serviceMonitor }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "imgproxy.fullname" $  }}
  {{- if .namespace }}
  namespace: {{ .namespace }}
  {{- end }}
  labels:
    imgproxy: "true"
    {{- range $key, $val := (.selector | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
    {{- range $key, $val := ($.Values.resources.common.labels | default dict) }}
    {{ $key }}: {{ $val | quote }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      {{- if .interval }}
      interval: {{ .interval }}
      {{- end }}
      honorLabels: {{ .honorLabels }}
  namespaceSelector:
    matchNames:
      - {{ $.Release.Namespace | quote }}
  selector:
    matchLabels:
      app: {{ $.Release.Name | quote }}
      imgproxy: "true"
  {{- if .targetLabels }}
  targetLabels:
  {{- range $label := .targetLabels }}
    - {{ $label }}
  {{- end }}
  {{- end }}
{{- end -}}
{{- end -}}
